name: ci

on:
  push:
    branches:
      - master
      - github-actions
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GH_TOKEN: ${{ SECRETS.GH_TOKEN }}
      GIT_AUTHOR_NAME: LiteX Robot
      GIT_AUTHOR_EMAIL: robot@timvideos.us
      GH_USER: symbiflow-robot
      GIT_MODE : https
    steps:
      - uses: actions/checkout@v2

      # Checkout Repository
      - name: Checkout
        run: git fetch --prune --unshallow --tags

      # Install Tools
      - name: Install Tools
        run: |
          sudo apt-get install wget build-essential python3
          pip3 install setuptools wheel
          pip3 install -r requirements.txt

      # Update
      - name: Update
        run: |
          sudo git config --system --replace-all user.email "$GIT_AUTHOR_EMAIL"
          sudo git config --system --replace-all user.name "$GIT_AUTHOR_NAME"
          ./update.py --push
